kind: pipeline
type: docker
name: default

steps:
- name: deploy
  image: plugin/npm
  pull: if-not-exists
  settings:
    username:
      from_secret: NPM_USERNAME
    password:
      from_secret: NPM_PASSWORD
    email:
      from_secret: NPM_EMAIL
  when:
    branch:
    - CP-1965_ci-deployment